sonar.organization=fatimah1403
sonar.projectKey=fatimah1403_InventoryTracker

# Project information
sonar.projectName=Inventory Tracker Secured
sonar.projectVersion=1.0

# Source code
sonar.sources=server,client/src

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/coverage/**

# Coverage (frontend only)
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
sonar.typescript.lcov.reportPaths=client/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
