name: ZAP Security Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://inventory-tracker-frontend-ten.vercel.app'
          fail_action: false
          allow_issue_writing: false  
        continue-on-error: true  
        
      - name: Move Report to Folder
        if: always()
        run: |
          mkdir -p zap_reports
          mv report_*.* zap_reports/ || true
          ls -la zap_reports/
          
      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_reports/